### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by emj365** [jugyo/SublimeRubyEval#7]
not work for me even I config ruby path

if the file not in project folder that I open in sublime will tell 'File not found in open folders'

event I save the rb file to open folder call the eval then nothing happened

**Comment by emj365** [comment]
sublime version is 2.0.2
check console find out:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./RubyEval.py", line 69, in run
  File "./RubyEval.py", line 50, in eval_as_ruby
TypeError: str() takes at most 1 argument (2 given)

**Comment by emj365** [comment]
fixed it https://github.com/jugyo/SublimeRubyEval/pull/10
